apiVersion: v1
kind: Service
metadata:
  labels:
    role: locust-master
  name: locust-master
spec:
  ports:
  - port: 5557
    name: locust-p1
  - port: 5558
    name: locust-p2
  selector:
    role: locust-master