apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: locust
    version: '9'
    component: slave
    role: locust-slave
  name: locust-slave
spec:
  replicas: 8
  selector:
    matchLabels:
      role: locust-slave
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: locust-slave
    spec:
      containers:
      - image: mudasar786/locustio:9-with-gui
        imagePullPolicy: IfNotPresent
        name: locust-slave
        envFrom:
          - configMapRef:
              name: locust-configmap
        command: ["locust"]
        args: ["--slave", '--locustfile=$(locustfile)', '--master-host=$(locust_master)', '-c $(no_of_clients)', '-r $(hatch_rate)']
        env:
          - name: locust_master
            value: locust-master
        volumeMounts:
          - mountPath: /scripts
            name: test-scripts
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: test-scripts
        configMap:
          name: tests-configmap
