apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: locust-slave
spec:
  replicas: 2
  parallelism: 2
  completions: 2
  template:
    metadata:
      labels:
        role: locust-slave
    spec:
      containers:
      - name: locust-slave
        image: mudasar786/locustio:9.3
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: locust-configmap
        command: ["locust"]
        args: ["--slave", "--no-web", "--only-summary", '--locustfile=$(locustfile)', '--master-host=$(locust_master)', '-c $(no_of_clients)', '-r $(hatch_rate)']
        ports:
        - containerPort: '5557'
          name: locust-p1
          protocol: TCP
        - containerPort: '5558'
          name: locust-p2
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 5557
          initialDelaySeconds: '3'
          periodSeconds: '30'
        readinessProbe:
          tcpSocket:
            port: 5557
          initialDelaySeconds: '3'
          periodSeconds: '30'
        env:
          - name: locust_master
            value: locust-master
        volumeMounts:
          - mountPath: /scripts
            name: test-scripts
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      volumes:
      - name: test-scripts
        configMap:
          name: tests-configmap